### PR TITLE
Update New Chinese Translate

### PR DESCRIPTION
**Pull request by PianCat**
Addon Root and Ambient Music Ticker Translate

### CODE REVIEW

**Comment by Sid-Sun** [comment]
@PianCat Your PR intrigues @Thenewguyhere

**Comment by PianCat** [comment]
@Sid-Sun Can you tell me what it means in detail? I don't quite understand

**Comment by sagarshah1729** [comment]
@PianCat Ignore it. That comment was posted here by mistake due to github bot. It was an internal joke, nothing else :)

**Comment by PianCat** [comment]
@sagarshah1729 Thanks U

**Pull request merged**
